### ISSUE TITLE
DomaConsorItemReaderがDomaのinternalな実装に依存している

### ISSUE THREAD

**Issue by nakamura-to** [lospatitos/springboot-batch-doma#1]
どんなことをしたいのかはわかりました。現時点でとにかく動作するものを優先するのであればこれでも問題ないと思います。

しかし、Domaのinternalな実装に依存していていたり内部のコードと重複していたりするため、Domaがバージョンアップした際に動かなくなる可能性が高いです。

https://twitter.com/nakamura_to/status/689799504950788097

上のツイートでDomaのDaoメソッドから返されるStreamが使えるのではないかと言いましたが、現在のDomaはDaoメソッドの終了時にはResultSetをcloseしているため、この案は有効ではありませんでした。

現時点では、DomaとSpring Batchの相性は良くないですね。もっと簡潔に組み合わせるにはDomaの側で対応が必要なようです。将来的なリリースに組み込む確約はできませんが、簡潔に組み合わせできるようにDomaの方で対応案を考えてみます。

**Comment by lospatitos** [comment]
迅速なご回答ありがとうございます。
今回、RDBMSがOracleのため、毎回ソートがかかり副問い合わせが発生するPagingBaseのItemReaderが使用できないため、CursorBaseItemReaderでDOMA2の良いところを生かせないか画策しております。
SpringBoot Web + DOMA2 は簡単な設定で動くので、Batchでも快適にDOMA2を利用したいです。

**Comment by backpaper0** [comment]
`SelectCommand`を拡張する案を考えてみました。
https://github.com/backpaper0/spring-batch-item-stream-reader-doma-sample

簡単に言いますと、DomaのSELECT系メソッドは`SelectCommand`というクラスの中で`ResultSet`(および`Connection`・`PreparedStatement`)の`close`を呼んでいます。
そして`SelectCommand`は`CommandImplementers`によりインスタンス化され、`CommandImplementers`は`Config`から返されます。

そこで、`ResultSet`を`close` **しない** `SelectCommand`を作って、それを返す`CommandImplementers`と`Config`を用意します。
DAO実装クラスはその`Config`を渡してインスタンス化し、SELECT系メソッド実行時には`ResultSet`を`close`せず、`ItemReader`が終了するタイミングで`close`するようにしてみました。

もし宜しければコードをご覧ください。

@nakamura-to さん、この案はいかがでしょうか？
これがそう悪い手でなければDoma側に手を入れる必要もなくなるかな、と思っています。

**Comment by nakamura-to** [comment]
@backpaper0 おもしろいアイデアですね！この考えは思いつかなかったです。要件満たせそうですね。

私はこんな感じのDaoメソッドの定義を認めるようにDomaに手を入れようかなぁと考えていました。

```
@Select
@Suppress(messages = Message.DOMA9999)
Stream<Book> select();
```

戻り値で `Stream` を返すのを認めるという案です。
ただし、そのままだとクローズ忘れが発生しがちなので注釈処理で警告メッセージを出し、その意味を理解して使うならば警告メッセージを `@Suppress` で抑制してもらうというものです。

backpaper0さんのはDomaに手をいれる必要ないですが設定が少し面倒になる。私の案はDomaの修正必要でDomaのコードの複雑性が増しますが使うのは楽。ですね。

ちなみに、私の案、実装がどれだけ大変かはまだちゃんと考えていないです。

**Comment by nakamura-to** [comment]
StreamをDaoメソッドの戻り値で返す上で述べた案を実装してみました。

domaframework/doma#122

次のリリースに含める予定です。
ご意見あればぜひお願いします。

**Comment by lospatitos** [comment]
@nakamura-to  さん対応ありがとうございます。申し訳ございません。github 使い慣れてなく
watchができていませんでした。 v2.7.0: 2016-02-27 試してみます。

**Comment by nakamura-to** [comment]
@lospatitos メンションすればよかったですね。ぜひ試してみてください。おそらく、やりたいことが比較的簡単なコードで実現できるんじゃないかなぁと思います。

**Comment by nakamura-to** [comment]
domaframework/doma#122 で回避できると思いますのでこのissueは取り下げます。
